### ISSUE TITLE
Updated to version 4.1.1 - GluonGui namespace not found error

### ISSUE THREAD

**Issue by ron77950** [RealityStop/Bolt.Addons.Community#78]
After updating to 4.1.1 (I was on 3.1.2 before) I get this error. 

`...\Bolt.Addons.Community-4.1.1\Editor\Fundamentals\Editors\ValueGraphSnippetEditor.cs(4,7): error CS0246: The type or namespace name 'GluonGui' could not be found (are you missing a using directive or an assembly reference?)`
